# Generated by Django 4.2.5 on 2023-10-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_desc', models.CharField(max_length=200)),
                ('product_img', models.ImageField(upload_to='image/proimg')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
