# Generated by Django 4.2.5 on 2023-10-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cateimg',
            field=models.ImageField(blank=True, null=True, upload_to='image/cateimage'),
        ),
    ]
